{ name = "web3-tests"
, dependencies =
  [ "aff"
  , "arrays"
  , "avar"
  , "bifunctors"
  , "console"
  , "effect"
  , "either"
  , "enums"
  , "eth-core"
  , "foldable-traversable"
  , "gen"
  , "integers"
  , "maybe"
  , "newtype"
  , "nonempty"
  , "orders"
  , "parallel"
  , "parsing"
  , "partial"
  , "prelude"
  , "profunctor-lenses"
  , "quickcheck"
  , "spec"
  , "strings"
  , "tagged"
  , "transformers"
  , "tuples"
  , "web3"
  ]
, packages = ./packages.dhall
, sources =
  [ "src/Contract/**/*.purs"
  , "test/**/*.purs"
  , "purescript-web3/test/web3/Web3Spec/Live/Utils.purs"
  , "purescript-web3/test/web3/Web3Spec/Encoding/ContainersSpec.purs"
  ]
}
